### ISSUE TITLE
container ip

### ISSUE THREAD

**Issue by fjzzmike** [qbanxiaoli/fastdfs#1]
IP=`ifconfig eth0 | grep inet | awk '{print \$2}'| awk -F: '{print \$2}'`; \n\
应该是 "\\\`", 需要转义。是在 docker run 获取 ip,二不是在 docker build 获取 ip
IP=\`ifconfig eth0 | grep inet | awk '{print \$2}'| awk -F: '{print \$2}'\`; \n\

**Comment by qbanxiaoli** [comment]
感谢指正，已修改，容器ip是当作环境变量传进去的，这句话是可以去掉的
