### ISSUE TITLE
去重功能似乎未生效

### ISSUE THREAD

**Issue by dreamfly32** [qbanxiaoli/fastdfs#10]
在docker内部上传同一个文件2次，建立了软连接，说明去重生效，
但是在外部，我用python上传同一个图片两次，没有建立软连接，说明去重没生效，
这就很奇怪？
![image](https://user-images.githubusercontent.com/32086491/147308419-4e70dcab-9537-4d03-a5fb-05b002c23c4c.png)

**Comment by qbanxiaoli** [comment]
用java试下了是可以的，python不清楚
