### ISSUE TITLE
如何新增group?

### ISSUE THREAD

**Issue by a18792721831** [qbanxiaoli/fastdfs#5]
如题：
现在是默认的group1
是否考虑一个新的环境变量，可以替换fastdfs中的group_name

在使用时，指定。
例如：
-e GROUP_NAME=group1/group2/...

**Comment by a18792721831** [comment]
可以增加一定的可扩展性，同时可以利用fastdfs的group思想，实现隔离。

**Comment by qbanxiaoli** [comment]
可以把配置文件挂载出来手动修改一下
