### ISSUE TITLE
fdhtd 启动报错

### ISSUE THREAD

**Issue by zhangxiang-1222** [qbanxiaoli/fastdfs#6]
ERROR - file: func.c, line: 332, local host does not belong to any group, program exit!

docker启动后 查看 fdhtd 日志报错如上。

fdht_servers.conf 配置如下
`group_count = 1
group0=xx.xx.xx.xx:11411`

ip地址是外网地址

**Comment by qbanxiaoli** [comment]
不支持外网地址，用内网
