### ISSUE TITLE
在使用公网ip时fdht日志会有一条报错 ERROR - file: func.c, line: 332, local host does not belong to any group, program exit!

### ISSUE THREAD

**Issue by sakiraven** [qbanxiaoli/fastdfs#8]
问题1.
linux环境下使用启动命令
docker run -d --restart=always --net=host --name=toolFastdfs -e IP=<公网ip> -e WEB_PORT=81 -v /home/ubuntu/docker-v/toolFastdfs:/var/local qbanxiaoli/fastdfs
在使用公网ip时fdht日志会有一条报错 ERROR - file: func.c, line: 332, local host does not belong to any group, program exit!(内网ip没有问题)

问题2.
参数--net=host在mac与win环境下无法使用,请问可以用什么代替

**Comment by sakiraven** [comment]
抱歉 自己没看仔细 compose完美解决问题

**Comment by kebukeYi** [comment]
咋解决的？我这个 也报这个错误了 【在使用公网ip时fdht日志会有一条报错 ERROR - file: func.c, line: 332, local host does not belong to any group, program exit!】
